app = "storj-gateway"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 7777
force_https = true
auto_stop_machines = "off"
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/minio/health/live"

